### ISSUE TITLE
rdfs:domain and range don't get exported

### ISSUE THREAD

**Issue by DanBerrios** [ontodev/robot#1025]
I've tried every way I can think of to export rdfs:domain and rdfs:range properties using export function.  None of them ever produce any exported info for the properties.  using "rdfs:domain" or the full property IRI doesn't produce any error message either.  It would be good to have these available for export....

**Comment by jamesaoverton** [comment]
As discussed over email, I think the problem is that OWLAPI handles domain and range like OWL logic and not as generic RDF predicates, but we neglected to cover these cases in the ROBOT `export` implementation. They would be a good addition, and should probably fit in this big case statement: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ExportOperation.java#L1147

**Comment by beckyjackson** [comment]
@jamesaoverton have you started on this? If not, I'm happy to do this one.

**Comment by jamesaoverton** [comment]
I haven't worked on this. If you have the time and the interest to implement it, that would be great!

**Comment by beckyjackson** [comment]
I’ll have time this weekend to take a shot at this :)
