### ISSUE TITLE
Single quote in label causes parse error in ROBOT template

### ISSUE THREAD

**Issue by sabrinatoro** [ontodev/robot#1053]
The following ROBOT template could not be merged: 
VBO id | label | Definition
-- | -- | --
ID | LABEL | EC %
VBO:0002448 | Blonde D'Aquitaine, United States of America (Cattle) | 'Blonde d\'Aquitaine (Cattle)' and ('located in' value wikidata:Q30)

The error message was: 
MANCHESTER PARSE ERROR the expression ('Blonde d'Aquitaine (Cattle)' and ('located in' value wikidata:Q211)) at row 415, column 11 in table "components/ncbibreeds.tsv" cannot be parsed: encountered 'Blonde d', but expected one of:
	Class name
	Object property name
	Data property name
	inverse
	not
	( ... )
	{ ... }

There was no error when using either `Blonde d\'Aquitaine (Cattle)` or `'located in' value wikidata:Q30` alone in the EC column. However, the combination of both led to the same MANCHESTER error. 

**SOLUTION that solved the problem:** 
replacing the EC column by using `CLASS_TYPE`:
VBO id | label | type | breed parent | location
-- | -- | -- | -- | --
ID | LABEL | CLASS_TYPE | C % | C 'located in' value %
VBO:0002448 | Blonde D'Aquitaine, United States of America (Cattle) | equivalent | Blonde d\'Aquitaine (Cattle) | wikidata:Q30

**Comment by sabrinatoro** [comment]
Thank you @matentzn for solving the problem! 

This issue was created for documentation purposes and can be closed. 
(I will leave it open for now in case someone wants to add a label-which I am not able to add)

**Comment by matentzn** [comment]
Awesome, thanks for documenting it! I would not say it's "solved", this solution is just a workaround that works for some reason only the ROGOD knows, but yeah, no one will work on the real issue since the workaround is good enough.

**Comment by matentzn** [comment]
We should also say that what you can't see here, of course we did "escape" the ' symbol like \'.

**Comment by matentzn** [comment]
Oh cool! I didnt know this was possible! Yes, agree, with now two totally fine workarounds, lets close this and let future generations figure it out.

**Comment by ramonawalls** [comment]
> Oh cool! I didnt know this was possible! Yes, agree, with now two totally fine workarounds, lets close this and let future generations figure it out.

I'm more of a past generation than a future one. :) I'm adding a vote fix this issue someday if possible. I have a template file with an equivalent class and a subclass column where for each the expressions do not follow a pattern. I'm working around it by substituting CURIES in place of all the labels, which is a pain, but manageable.

Since the problem can't really be fixed, could you please add more information to the documentation under http://robot.obolibrary.org/template#manchester-parse-error? A link to this issue would have save me a lot of time in troubleshooting. Finding relevant issues on their own can be very challenging.

**Comment by ramonawalls** [comment]
@matentzn here are examples of templates I am using where the single quoted labels don't work because (I think) I need an input file.

This commit message shows the template in its 'text label' and curie form:

https://github.com/PlantPhenoOntology/ppo/commit/d9007578ed1662220151dae513d92539a68dc022#diff-835848f5875fd347676b6c8de1a45b3cdac86774e196c9c0fc58769155ee2614

Here is another example with a different axiom but the same problem:

https://github.com/PlantPhenoOntology/ppo/commit/dd48eb4a16b1c75aa2926332e1f5ae719cbe44fd#diff-c225e9edf5871288e0c260aef4f27ebd9c21f8b83552f0f448b598499936a9ce

The error I am getting is:
```
MANCHESTER PARSE ERROR the expression (((OBI:0000293 some PO:0000003) and (OBI:0000299 some (IAO:0000027 and (IAO:0000136 some PPO:0002000))))) at row 7, column 7 in table "../templates/PPO_supporting_classes.tsv" cannot be parsed: encountered unexpected 'some'
	hint: the term before 'some' must be a property
```
