### ISSUE TITLE
include datatype propery values in template

### ISSUE THREAD

**Issue by luisramosbosch** [ontodev/robot#1126]
I am trying to add some datatype property values to individuals (postal code number), but when I use the following template:

```tsv
CURIE	Label	Type	Comment	hasPostalCode	
ID	LABEL	TYPE	A rdfs:comment	hasPostalCode				
goo:047F	sample organization	org:OrganizationalUnit	organizational Unit sample	94315	
```

Robot sends me the following error:

UNKNOWN TEMPLATE ERROR could not interpret template string "hasPostalCode" for column 4 ("hasPostalCode") in table "org-with-add2.tsv".

It is evident that the issue is in "hasPostalCode" datatype property, but the question is then which is the proper notation for representing datatype properties in templates?. I had the same issue using the prefix gleif, or the full namespace (https://www.gleif.org/ontology/Base/) with the property name.

Thanks in advanced

Luis Ramos

**Comment by jamesaoverton** [comment]
I updated your example table to use a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) so that I could read it properly.

Your row is defining an OWL Individual, so please look at this section of the ROBOT Template documentation <http://robot.obolibrary.org/template#individual-template-strings>. You want to use `I hasPostalCode` to assert a value for this data property.

**Comment by luisramosbosch** [comment]
solved, thanks!.
