### ISSUE TITLE
Add ability to do SPARQL construct

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#159]
Following up from
https://github.com/ontodev/robot/issues/24#issuecomment-225994582

not sure if this should be new command or a `--construct` option on query

**Comment by jamesaoverton** [comment]
My intention was to provide `--select` (implemented), `--ask`, `--verify`, and `--construct` options on query, because the semantics are very different. `--verify` would be like `--ask` but would exit on failure.

But I'm willing to be convinced of a better design.

**Comment by cmungall** [comment]
sounds good to me

**Comment by dougli1sqrd** [comment]
I'm a little confused. Why are there command line options for different sparql constructs? Can you not merely run the query, and let the query (which might have `CONSTRUCT`, `SELECT`, etc) results come back? A separation like between just querying and verifying could make sense, cause then you're drawing a line between actual ROBOT behavior: in the first case we just run the query, and the second we check if the query results are correct.

**Comment by cmungall** [comment]
I'm OK with introspecting the behavior, but the main drawback is it 
leads to possible unpredictability. If the options are explicit there is 
less chance of unexpected behavior. What about both? If nothing 
specified, introspect. If option passed, use it. What do you think 
James?

**Comment by balhoff** [comment]
I know you mean the other James, but I'll just make a comment. :-) Most of the RDF APIs I've used have separate methods for executing SELECT vs CONSTRUCT vs ASK, etc., I think primarily because the return types are completely different: result iterator vs graph vs boolean. That's probably more important in a type-safe programming language compared to a command line that is text in and text out. Not sure if that sways the decision either direction.

**Comment by jamesaoverton** [comment]
Yes, just like  @balhoff said, Jena uses different methods and I was following their lead. Also, I only needed SELECT, so that's all I implemented.

I don't mind introspecting, but I haven't looked for a library method to do that.

It would be great to see some examples of the CLI calls everyone wants to make.

**Comment by dougli1sqrd** [comment]
Ah, okay. It's just that a user could use a CONSTRUCT query when passing the `--select` option, or `--construct` when using the CONSTRUCT query. In the sense that a user wants to make a query, and they expect back some data from the server, both of these are the same. I understand they're different structured data in the end. @cmungall I think that sounds a little much inspecting the query text itself to see what it is. And @balhoff yeah that makes sense now why they have different functions (methods) for dealing with the different query types, as the results are different types in the API. Hmm. Yeah I think from a user's perspective, they just want a blob of text back that has their results. But we're sorta stuck with the API. So `--construct` could be fine for now.

**Comment by dougli1sqrd** [comment]
@jamesaoverton 
As an example of a command line call I was thinking maybe something like:

`robot query -i path/to/ontology.owl -q path/to/query.rq` which would run the query against the owl and just dump the data in a file or stdout.
Then to verify something:
`robot query -i path/to/ontology.owl -q path/to/query.rq` which could exit status if something is returned, or we could the results against some test (contains x, etc).

But that seems more difficult since we'd have to figure out which data type to put the results in. For now we could just do the --construct and --verify bit?

**Comment by jamesaoverton** [comment]
Yes, I think `--construct` and `--verify` are fine for now.

I assume the second example should be `robot verify -i path/to/ontology.owl -q path/to/query.rq`.

One thing to keep in mind is that it can be expensive to load an ontology, and we often want to do more than one thing with it, so ROBOT chains commands and keeps the ontology in memory. Loading into the (in-memory) triplestore can also be expensive, but currently we do not keep the triplestore after the `query` command is done -- chains currently just pass the ontology to the next command. The current design allows multiple `--select query.rq result.csv` pairs in a single `query` command, avoiding the chaining issue.

**Comment by dougli1sqrd** [comment]
Okay, check out https://github.com/ontodev/robot/pull/164
