### ISSUE TITLE
Extracting classes that have a certain annotation property.

### ISSUE THREAD

**Issue by msinclair2** [ontodev/robot#199]
What is the best way to extract out all classes (and the properties used in their definition) that have a certain annotation property attached to them (for example, owl:deprecated or some other boolean flag-type property)?

Thanks.

**Comment by jamesaoverton** [comment]
By “extract” do you mean: just get a list? create a new module with just those classes? remove those classes from the ontology? Because you mention owl:deprecated, I suspect you mean the third option.

For any of those options, I would start with `robot query` with SPARQL to get a list of the target classes. If you just want a list, then you’re done. If you want to create a new ontology with the selected classes, you could feed the list to `robot extract`.

If you want to remove the listed classes from the ontology, well unfortunately ROBOT does not have a command to do that, but we probably should have one.

**Comment by cmungall** [comment]
Removing listed classes: I would see this as being folded into a general command for extracting subsets (in the obo sense, aka slim). Removing a set of classes is just the same as extracting the complement set.

Could this be done extending the existing `extract` command? That may result in complexification of options.

in owltools this was done by

```
--extract-ontology-subset [-i FILE][-u IRI][-s SUBSET][--fill-gaps]        performs slimdown using IDs from FILE or from named subset
```

**Comment by jamesaoverton** [comment]
I think we need something like this. I'll close this issue and we'll work on it in #183 instead.
