### ISSUE TITLE
Clean up JavaDocs

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#210]
We should try to fix the JavaDocs so that `men site` runs properly.

**Comment by rctauber** [comment]
Cleaned up the JavaDocs (commit on my fork), and the docs generate fine. `mvn site` still throws errors because links between modules don't work. It should work fine when we go on to stage/deploy.

This might be more relevant to #34 and #211, but do we have somewhere to deploy the site (`distributionManagement`)?

**Comment by cmungall** [comment]
once #34 is done javadocs module-level should auto-propagate to http://www.javadoc.io/

**Comment by rctauber** [comment]
Thanks @cmungall - should I do a PR for the JavaDocs fixes?

**Comment by cmungall** [comment]
Yep, go ahead and make a PR, thanks!

(we haven't really decided on our best practices with PRs, I like to make PRs early and mark with WIP if not ready, makes it easy to see what's going on, others prefer PRs only when ready to merge)

**Comment by jamesaoverton** [comment]
Fixed by #218.
