### ISSUE TITLE
MireotOperation doesn't include all annotation properties when they come from imported ontologies in the input ontology

### ISSUE THREAD

**Issue by agbeltran** [ontodev/robot#235]
Currently, the MireotOperation that does not consider the case when the input ontology imports other ontologies. In that case, the MIREOTed module should include the annotations coming from the imported ontologies, but this is not the case.

**Comment by jamesaoverton** [comment]
I'm not sure that this is what ROBOT should do. I find that people have differing expectations about whether the import closure should be included when running various operations.

I usually `merge` before `extract` to be sure that the imports are included. Chaining commands makes this easy. We could consider adding another option flag for including imports in `extract`.

**Comment by agbeltran** [comment]
I see what you mean, but I would have thought that the MireotOperation should handle this directly. I have got a test case to demonstrate this that I can send you in a PR. Maybe you can show me how you would chain the commands for that test case.

**Comment by jamesaoverton** [comment]
[Chaining commands](https://github.com/ontodev/robot/tree/master/examples#chaining) works like this:

```
robot merge --input uberon_fragment.owl \
    extract --method MIREOT \
    --upper-term "obo:UBERON_0000465" \
    --lower-term "obo:UBERON_0001017" \
    --output results/uberon_mireot.owl
```

I think there will be valid use cases both for including the import closure and for not including it. So we need to support both somehow. We're also careful not to change behaviour in ways that would break existing systems. But adding an option flag is possible.

Does the MIREOT paper talk about this? Are there other implementations that we can compare?

**Comment by agbeltran** [comment]
Thanks @jamesaoverton for the example and pointer to the chaining commands documentation.

Indeed 
```
robot merge -I "http://purl.obolibrary.org/obo/ro.owl" \
          extract --method MIREOT \ 
          --upper-term "obo:RO_0001000" \ 
          --lower-term "obo:RO_0001000" \ 
          --output ro-mireot-cmd.owl
```
produces what I was expecting.

As per other implementations, OntoFox brings in the import closure directly.

I think that an option flag for the extract method might still be useful.

**Comment by jamesaoverton** [comment]
I don't think that OntoFox is a good comparison case. My understanding is that all the OntoAnimal tools run against a shared triplestore, and that each ontology is merged with its imports into a single graph when they are loaded into that triplestore. So OntoFox cannot distinguish the import closure. I could be wrong -- as far as I know, their loading code is not open source.

ROBOT is built on OWLAPI, which clearly distinguishes between operations on the ontology (alone) and operations on the ontology plus its import closure.

My current thinking is that chaining is more clear and a better separation of concerns than a flag. I would prefer to avoid adding a flag to every command. Since you've used ROBOT before but didn't know about the chaining option, it clearly needs better documentation.

If you still think a flag is better, please suggest what it should be called and how it should work.

**Comment by agbeltran** [comment]
I see what you mean and chaining seems to cover the use cases I have in mind, so I will close this issue. Thanks!
