### ISSUE TITLE
is_a path between lower and upper terms 

### ISSUE THREAD

**Issue by citmejia** [ontodev/robot#282]
Hi,

Is there a way to use robot to extract a specific path between two nodes? I was using MIREOT method, but it seems to extract not only all possible paths between upper and lower terms, but also all paths to the root. For example, on Ontology of Microbial Phenotypes,  I used upper term **population growth phenotype**
and lower terms **faster growth rate** and **slower growth** rate. I got the module shown in the image. However, I only need the path that goes from **slower growth rate** and **faster growth rate** to **population growth phenotype** passing through **growth rate phenotype**, not the path that goes through **altered population growth**. Neither do I want all paths to the root.

![image](https://user-images.githubusercontent.com/33327131/38946120-21c0f732-42fe-11e8-9caf-ead42cf327c7.png)

**Comment by rctauber** [comment]
It looks like the reason you're retrieving up to the root node is because 'altered population growth' is a subclass of both 'population growth phenotype' and 'altered biological process'. Your `upper-term` isn't one of the ancestors of 'altered biological process', so the MIREOT method retrieves the ancestors to that root ('microbial phenotype').

We are working on `filter` in #272, which works perfectly to filter nodes (e.g. get the path from 'population growth phenotype'). It is possible to have upper and lower bounds like you specified here, but it's not as simple of a command:
```
robot filter --input omp.owl --entities entities.txt \
      --select "self descendants" --select "self ancestors" \
      --output omp-ext.owl
```
The entities file contains the CURIES for 'population growth phenotype', 'slower growth rate', and 'faster growth rate'. The first `select` gets all the descendants (including your input terms). The second gets all the ancestors from the output of the first `select` (including your input terms), essentially filtering out the siblings of your lower terms.
![image](https://user-images.githubusercontent.com/16750150/39050762-25f4afec-44d9-11e8-9cff-f1b0c279434a.png)

This is not yet in the release of ROBOT, it's just a feature we are working on. Sorry this was such a long-winded response, please let me know if you have any questions!

**Comment by rctauber** [comment]
Hi @citmejia - I wanted to follow up and see if you were able to solve this problem. `filter` is now available in our pre-release: https://github.com/ontodev/robot/releases/tag/v1.2.0-alpha-1

Please let me know if you have any other questions!

**Comment by citmejia** [comment]
Hello Rebecca,

I have not tried the most recent version of robot yet. I will resume this
project soon and I'll let you know.


2018-08-14 11:37 GMT-05:00 Rebecca Tauber <notifications@github.com>:

**Comment by rctauber** [comment]
Were you able to resolve this @citmejia ? Thanks!

**Comment by citmejia** [comment]
Hi,

Yes, but it was a little more complicated. The new filter command was
helpful. I realized I necessarily needed a middle term to select just one
of the multiple paths to the upper term I wanted. So, what I did was:

robot extract --method MIREOT -I http://purl.obolibrary.org/obo/omp.owl -u
http://purl.obolibrary.org/obo/OMP_0007085 -L omp_terms.txt  filter -t
http://purl.obolibrary.org/obo/OMP_0007085 --select "annotations self
descendants" --output omp_first_module.owl

robot extract --method MIREOT -I  http://purl.obolibrary.org/obo/omp.owl -u
http://purl.obolibrary.org/obo/OMP_0000000 -l
http://purl.obolibrary.org/obo/OMP_0007085 --output omp_second_module.owl


robot merge --input omp_first_module.owl --input omp_second_module.owl
--output omp_module.owl


Best regards,

Cit

Le mer. 30 janv. 2019 à 10:52, Rebecca Tauber <notifications@github.com> a
écrit :

**Comment by rctauber** [comment]
Glad you got it sorted out! Do you have any more questions/issues with this or can we mark this as resolved?

**Comment by citmejia** [comment]
You can mark it as resolved. Thanks!

Le jeu. 14 mars 2019 à 12:27, Rebecca Tauber <notifications@github.com> a
écrit :
