### ISSUE TITLE
Proposed new check: replaced_by should only be used on deprecated classes

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#288]
I will do this when #267 is done

**Comment by rctauber** [comment]
`report` has a misused-obsolete-label check: http://robot.obolibrary.org/report_queries/misused_obsolete_label

Should we add a check for replaced_by as well?

**Comment by matentzn** [comment]
Our HP QC pipeline keeps flagging this one up:

```
HP QC keeps having this entry:ERROR	misused_obsolete_label	HP:0031859	rdfs:label	obsolete synonym 
```

Is QC complaining here the right way?

**Comment by jamesaoverton** [comment]
The check looks for term with labels that start with "obsolete" but are not owl:deprecated, and vice versa. Usually that's a mistake that we want to catch. In the case of HP:0031859 it's intentional.

I'm not sure what the cleanest way to handle this sort of exception. Exceptions add complexity. It seems crude to build the exception into ROBOT's SPARQL file. We could have a per-project exception list, but we also want the new OBO Dashboard to know about legitimate exceptions. I dunno.

**Comment by matentzn** [comment]
I am not too bothered by this here; most of my pipelines deal with exceptions using unmerge: I have an owl file with axioms I want to explicitly exclude from QC, which I unmerge from my ontology before running robot report; I am happy to continue to do that for now, just wanted to make sure that the behaviour is intentional.

**Comment by matentzn** [comment]
Proposed query:

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
 VALUES ?property { <http://purl.obolibrary.org/obo/IAO_0100001> }
 ?entity ?property ?value .
 FILTER NOT EXISTS { ?entity owl:deprecated true }
 FILTER (?entity != oboInOwl:ObsoleteClass)
}
ORDER BY ?entity
```
