### ISSUE TITLE
reason command should not inject class axioms for external classes

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#296]
Currently when running `reason` on an ontology A that imports B, it is possible for axioms of the form `B1 SubClassOf B2` to be injected into A.

This can sometimes be desirable, but usually not. We should add a boolean option `--exclude-external-entities`

The precise logic is not necessarily straightforward. How do we determine what is external? Should this be based on explicit declaration axioms? Occasionally these leak into the main ontology. But this still seems more reliable that making any additional assumptions (e.g. but URI structure, or presence of other axioms).

What about edge cases, where we may infer an axiom spanning A and B?

I propose a simple test whereby for any class axiom, the class signature of the inferred axiom must overlap with the declarations of the main ontology by at least one class. If `--exclude-external-entities` is true, then anything that does not pass this is dropped.

**Comment by rctauber** [comment]
If the axiom has one class that is in the declarations, but multiple other classes that are not in the declarations, do we still want to include it? If I set `--X true`, I would assume that *all* external entities would be excluded. Instead of true and false, we could do something like `--external-entities`...
* `all`: include all entities
* `some`: include axioms with at least one entity in the declaration
* `none`: include only axioms with entities in the declaration

Default to `all`? Then again, `true`/`false` is a little less complicated, but this gives more flexibility...

**Comment by cmungall** [comment]
I think the directionality is important - a common scenario is subclassing an ontology, you'd want the  inferred subClassOf axioms pointing to parents in the more general ontology.
