### ISSUE TITLE
Command query --output option

### ISSUE THREAD

**Issue by agbeltran** [ontodev/robot#306]
This is minor, but most commands require to indicate the output file through the ```--output``` option (e.g. ```annnotate```, ```convert```, ```extract```), while the ```query``` command doesn't specify this option:
```usage: robot query --input <file> --query <query> <output>```

I see it does have the option ```-O, --output-dir``` but for consistency with the other commands, it would be good if it had the ```--output``` option too.

**Comment by jamesaoverton** [comment]
Thanks, this kind of feedback is very helpful.

You’re right that the usage is different here. It was a deliberate choice. Our reasons are:

1. Everywhere else the `--output` is an ontology file, but here it’s usually a table.
2. You can specify multiple `--query` options, and each needs a separate output path, or an output directory for all queries. A single `--output` option either causes conflicts or makes the single-query case quite different from the multi-query case.

I think those are good reasons to keep the current behaviour.

**Comment by agbeltran** [comment]
ok, makes sense - thanks for clarifying!

**Comment by agbeltran** [comment]
Following up, if the criteria is that ```--output``` is used to produce ontology files, shouldn't ```diff``` not have that option as it produces some text listing the differences?

```usage: robot diff --left <file> --right <file> --output <file>```

Another minor thing for ```diff```, the command uses left and right and then the output refers to ontology 1 and ontology 2. Thanks!

**Comment by jamesaoverton** [comment]
You're right that `diff --output` isn't consistent with the rest. That's one the oldest ROBOT commands. We strive for consistency, but sometimes mess things up. Backwards compatibility is even more important than consistency, especially when it comes to interfaces, because we don't want to break working code that relies on ROBOT.

We could probably change "ontology 1" and "ontology 2" to "left" and "right" without breaking stuff.

**Comment by agbeltran** [comment]
Got it - thanks!
