### ISSUE TITLE
Ignore import declarations for some commands

### ISSUE THREAD

**Issue by mark-jensen** [ontodev/robot#310]
I've noticed that certain commands (eg- `diff`, `extract`) will throw exception "could not load imported ontology". Adding the import file to the directory with the source file doesn't fix the problem, but removing the import declaration in the source file obviously does.

1. Is it necessary to load import files? If so, any thoughts on why mine aren't? I can provide more details if needed. 
2. Is this behavior necessary? Could it be optional? 
               Eg- `Robot diff --left Old.ttl --right New.ttl --ignore-imports` 

FYI, I've just started using Robot. Apologies if I missed something in the documentation or previous issues.

**Comment by jamesaoverton** [comment]
Imports can be tricky. ROBOT (like Protégé) uses the `catalog-v001.xml` file to override import statements, letting you use local copies instead of loading from the specified IRI. If you're not familiar with catalog files, I can provide some pointers.

It would be possible for ROBOT to ignore imports, but it would take some work and I'm not sure how useful it would be.

For comparing Turtle files, plain old `diff` might be more useful than `robot diff`, depending.

**Comment by balhoff** [comment]
> It would be possible for ROBOT to ignore imports, but it would take some work and I'm not sure how useful it would be.

It's also important to keep in mind that for RDF formats, not loading imports can result in incorrectly loaded ontologies. Without property declarations, RDF can mix up object and annotation properties.

**Comment by jamesaoverton** [comment]
Good point @balhoff !

**Comment by rctauber** [comment]
You could also remove import statements if you need to with: 
```
robot remove --input foo.owl --select imports --output bar.owl
```

Adding `--trim true` will also remove dangling entities left behind, if there are any.

**Comment by jamesaoverton** [comment]
Yeah, I think `remove` (in <https://github.com/ontodev/robot/releases/tag/v1.2.0-alpha-1>) is the right way to go. I'll close this.

@mark-jensen If you have any trouble with @rctauber's suggestion, let us know!
