### ISSUE TITLE
Better explanation for "module"

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#339]
Our explanation and links for SLME on <http://robot.obolibrary.org/extract> aren't very helpful. Can somebody who knows more about this than I do add a paragraph saying what "module" really means, and the difference between STAR, TOP, BOT.

This site has too much information: http://owl.cs.manchester.ac.uk/research/modularity/

**Comment by matentzn** [comment]
A user-friendly definition goes something like this:

The seed is the list of terms supplied to the extract command (i.e. term-file).

TOP: The TOP-module contains mainly the terms in the seed, plus all their *sub*-classes and the inter-relations between them. The module is called TOP because it takes a view from the TOP of the class-hierarchy downwards. Modules of this type are typically large and should only be used if there is a need to include all sub-classes in the module.

BOT: The BOT, or BOTTOM, -module contains mainly the terms in the seed, plus all their *super*-classes and the inter-relations between them. The module is called BOT (or BOTTOM) because it takes a view from the BOTTOM of the class-hierarchy upwards. Modules of this type are typically of a medium size and should be used if there is a need to include all super-classes in the module. This is the most widely used module type - when in doubt, use this one.

STAR: The STAR-module contains mainly the terms in the seed and the inter-relations between them (not necessarily sub- and super-classes). Modules of this type are typically very small and should be used if the module needs to be of minimal size containing only (or mostly) the classes in the seed file. 


As a side note: Maybe we should think about using STAR modules with a bit of smart SPARQLing to avoid the 'pulling in' of classes that are in branches of the ontologies that are not important, but happen to be referenced by some existential restriction.

Example: If using BOT with seed {A}, and you encounter the axiom A sub R some B, the whole B branch (including all its super-classes) will be pulled into the module.

**Comment by balhoff** [comment]
Should this definition also state that the module will contain all the axioms needed to provide the same entailments for the seed terms as the full ontology would? Is that correct, @matentzn? And is that true for any of TOP, BOT, and STAR?

**Comment by matentzn** [comment]
Yeah, this phrase 'the inter-relations between them' tried to gloss over the fact that some of these relationships might not be asserted.. @jamesaoverton Do you prefer the definition to include the phrase 'preserve entitlements between elements in the signature'? This can be added as a general statement just before the definition, because it holds for all module types, e.g.:

All three module types ensure that any entailments between entities (classes, properties and individuals) that are mentioned in it are preserved. For example, if an ontology implies that A is a subclass of B, or A is part of B, and the module contains A and B, then the module will also imply that A is a (or is part of) B.

**Comment by dosumis** [comment]
> Do you prefer the definition to include the phrase 'preserve entitlements between elements in the signature'?

+1

**Comment by cmungall** [comment]
I am not reopening this but just wanted to demonstrate something who may end up here via a search.

I find it completely bonkers how BOT will always include all individuals and their types, even if there is no possible graph connection to them from the seed. 

To demonstrate, see myont.ttl:

```ttl
@prefix entity: <http://www.wikidata.org/entity/> .
@prefix   rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

entity: rdf:type owl:Ontology .

entity:Q3455524
    a owl:Class ;
    rdfs:label "administrative region"@en .

entity:Q2317999
	a entity:Q482994 ;
	rdfs:label "Definition of Real"@en .

entity:Q482994
	rdfs:label "album"@en .
```

```bash
$ robot extract -i  myont.ttl  -t http://www.wikidata.org/entity/Q3455524 -m BOT -o mod.ttl
```

The resulting ontology mod.ttl will be identical to the input. It includes Q2317999 despite this having no graph connection to the seed.

Our fantastic docs warn of this (thanks Nico!) but I wonder if the warning could not be made more prominent, as this is massively counter-intuitive.

Way before I started using SLME I would do a simple graph walk from the seed over the relational graph.

Was this guaranteed to be entailment-preserving? Absolutely not! Was it good enough for reasoning? Probably! Did it satisfy the end-user use case of having a walkable graph with only relevant portions of external ontologies? Yes!!!

I think we have confused use cases here, and we should be using an intuitive easy-to-describe algorithm for the end-user graph-walk use case (where the ontology is pre-reasoned in any case). I think very few people understand SLME. Everyone understands graph traversal.

**Comment by dosumis** [comment]
> Was this guaranteed to be entailment-preserving? Absolutely not! Was it good enough for reasoning? Probably! Did it satisfy the end-user use case of having a walkable graph with only relevant portions of external ontologies? Yes!!!

> I think we have confused use cases here, and we should be using an intuitive easy-to-describe algorithm for the end-user graph-walk use case (where the ontology is pre-reasoned in any case)

+100

**Comment by matentzn** [comment]
I agree the handling of individuals is counter-intuitive; I reached out to some DL people to find out whether there is a way to handle this better.

> I think we have confused use cases here, and we should be using an intuitive easy-to-describe algorithm for the end-user graph-walk use case (where the ontology is pre-reasoned in any case).

In agreement with @cmungall and @dosumis , I think that we need a better algorithm that includes only ABox axioms somehow **relevant to the seed**; but I very strongly believe that is algorithm should be (1) based in logic rather than graph traversal and (2) be entailment preserving. I will keep you posted on what I find out.

**Comment by jamesaoverton** [comment]
`extract` has an `--instances` option that lets you exclude individuals from SLME extraction and supports the behaviour @cmungall wants: http://robot.obolibrary.org/extract#instances -- I think! It basically removes instances, then runs SLME, then restores the instances selectively. See #185 and #385.

Maybe this isn't quite what you want, but it's something.

**Comment by cmungall** [comment]
@jamesaoverton `--instances` works for some use cases, but if we need to seed from an abox then we're stuck see #557

**Comment by matentzn** [comment]
@jamesoverton @cmungall FYI: I am currently in touch with Uli and Bijan from Manchester to see if we create a variant of SLME algorithm that works for SRIQ, i.e. all of OWL **_apart_** from nominals (aka individuals used in class expressions, such as `A subclass of {i,r}`, where i and r are individuals. I think nominals are the reason why SLME is specified in this weird way that you experience. This is not going to be solved super soon,  but we are on it (will forward emails).

**Comment by jamesaoverton** [comment]
@cmungall Yeah, I misunderstood, but #557 makes it clear.

@matentzn Thanks. This sounds like a general problem that would be good to solve in OWLAPI.
