### ISSUE TITLE
Filter problems

### ISSUE THREAD

**Issue by Clare72** [ontodev/robot#376]
Was having some trouble using the 'filter' function, so I decided to try some of the examples from the doc:

>robot filter --input obi.owl --term OBI:0000070 --term rdfs:label --output output.owl

works fine.

>robot filter --input obi.owl --term OBI:0000070 --select annotations --output output.owl

output.owl has no terms when I open it in Protege.

>robot filter --input obi.owl --term OBI:0000070 --output output.owl

wasn't in doc examples, but I thought it might do someting and it doesn't give me any terms.

>robot filter --input obi.owl \
  --select "owl:deprecated='true'^^xsd:boolean" --trim true --output output.owl

from the 'remove' command examples doesn't seem to work with 'filter' (no terms).

If I am doing something wrong, please can you improve the doc?

**Comment by rctauber** [comment]
Hi @Clare72 ! Thank you for bringing this to our attention.

The second example:
```
robot filter --input obi.owl --term OBI:0000070 --select annotations --output output.owl
```

Isn't quite correct. It should be:
```
robot filter --input obi.owl --term OBI:0000070 \
  --select "self annotations" --output output.owl
```
I'll update this in the docs!

If there is no `--select` included, the default is `self`, which means the input term or terms will be selected. When you just say `--select annotations`, ROBOT doesn't understand to select the input term as well unless you say so. 

The reason why the following doesn't work:
```
robot filter --input obi.owl --term OBI:0000070 --output output.owl
```

Is that the annotation properties are not being included in the filtered output.

Filter is a little tricky because the annotations aren't included unless you explicitly say so (e.g. `--term rdfs:label`), or include `--select "self annotations"`.

**Comment by rctauber** [comment]
I'm going to close this issue since the docs have been updated. @Clare72 - please feel free to re-open if you have any other problems. Thanks!
