### ISSUE TITLE
New option proposal: split

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#39]
I would like to have an operation for auto-modularizing an ontology. Note this is distinct from module extraction, but not unrelated. The goal is to split a monolithic ontology into two or more modules based on some kind of organization criteria.

One of the drivers for this is slightly artificial: file size limits on github for large OWL releases.

The input would be an Ontology. This may be have an import chain or may be standalone. The output would be a set of Ontologies `o1...on`. These would all form a connected import graph with a single root. Ideally this would be or be easily turned into a OWL/ZIP file, see owlcs/owlapi#375

We can imagine a few strategies. The two obvious ones to me are 
1. axiom-type based
2. content-based

For axiom type-based we could simply have a file for every axiom type (e.g. SubClassOf). Some could be further partitioned: e.g. axiom types such as AnnotationAssertion could be further split based on the AnnotationProperty.

Content type would ideally magically make biologically meaningful modules. E.g. an anatomy ontology would split by organ system. However, it's far from being this simple, many partitions overlap, and there may be axiom cross-talk between partitions, defeating the point of modularization. It seems this is best done manually or at least semi-automatically, and is a good long term goal for ontologies but not doable in this ticket. @sesuncedu has previously alluded to some kind of automatic technique for splitting an ontology.

I assume there has been a lot of theoretical work on this, but the theoretical work has not made it's way back into robust tooling.

We can make a distinction here between source and release files. There may be different use cases depending for source and release modules, and the modules used by source developers may be different from the modules required by release consumers.

For the immediate use case I have in mind, the source of the ontology is .obo (compact, monolithic, easily diffed) and the derived .owl is much larger hence the need to split somehow. I acknowledge this applies to a decreasing number of projects. Longer term, for ontologies maintained as .owl, we will need to switch to modularized source, but one difficulty here is ensuring axioms stay in the right module (it's not quite as easy as editing in Eclipse). Strategies involve modifying Protege, post-save hooks to reorganize axioms into modules or simply discipline. This is out of scope for this ticket but worth mentioning as context. Particularly, option (2) makes more sense than (1) for source modules. However, there may be projects where (1) makes sense for source. E.g. non-logic oriented editors edit textual descriptive properties in the AnnotationAssertion module, core developers edit SubClassOf EquivalentClasses module, advanced developers edit GCI, propertyChain, etc.

Currently this ticket is more for discussion than implementation.

cc @dosumis @mcourtot

**Comment by mcourtot** [comment]
I think there are 2 distinct cases here:

(1) problem with the file size: if this is the main driver (the immediate use case) then splitting arbitrarily an OWL file into multiple ones shouldn't be an issue (assuming we don't intend for each OWL file to be a valid ontology). I would call such an option "split". I'm not even sure we'd need to consider axiom-based, because there are few chances that such as a plot has any biological meaning associated and I can't think of an advantage to having specific types of axioms into specific files. Also there is no guarantee the axiom-based split is not itself over the allowable size. Re different types of users - the resources I am familiar with have a set of editors who do it all. I can imagine cases where we'd want for extract per user type (such as TermGenie and template/freeforms) but it seems this is a rarer case, maybe not motivating at this stage?

(2) having meaningful subsets of the ontology: this seems very similar to what Ontodog does at release time. For editing purpose, it is akin to the old way of managing branches in OBI, and this came with quite a lot of pain: there were issues with selecting the right file in Protege, making sure axioms were stored in the correct file, and it was very hard to do an update across files.

If the current use case is OBO, is it possible to split the OBO and then do the OWL conversion? Or is it better to convert the whole OBO and then do the split?

**Comment by cmungall** [comment]
> If the current use case is OBO, is it possible to split the OBO and then do the OWL conversion? Or is it better to convert the whole OBO and then do the split?

I think the end result is the same? When I say the use case is obo I mean projects that manage source in obo. These groups are happy with a relatively compact and VCS friendly source, and only hit large file issues at release time for the RDF/XML-OWL version. If a project is managing source as a W3C OWL format and the ontology is large then they may be forced to modularize at source time, prior to release time. For example, if GO is to migrate to github and switch source to OWL then we will be forced to modularize at source time.

**Comment by cmungall** [comment]
I'm happy with `split` as the name, [it has a good precedent](http://unixhelp.ed.ac.uk/CGI/man-cgi?split).

axiom-based split has many advantages over a random split, e.g. lessening VCS churn and making the diffs (partly) more interpretable.

**Comment by cmungall** [comment]
'decomposition' is also a term used, e.g. in the [OWL/ZIP paper](http://ceur-ws.org/Vol-1265/owled2014_submission_6.pdf)

That's a bit overloaded for us (we often use it in the sense of *class* composition/decomposition), so I suggest avoiding this term.

**Comment by cmungall** [comment]
Command: split

Core Options:

 * by-subject-source `SS`
 * by-axiom-type `AT`
 * by-target-source `TS`
 * by-object-property `OP`
 * by-annotation-property `AP`

These are not mutually exclusive

The resulting ontology IRI and filename is determined by a concatenation of these:

   BASE{-SS}{-AT}{-OP}{-AP}{-TS}.owl

Where braces indicate optionality.

The set of all split ontologies must exhaustively and mutually exclusively cover the input ontology

Only certain axioms should go into a `P` partition, axioms that use the P rather than are about the P

Does this feel appropriate for robot? An argument can be made that this is both too niche and overloads too much customization into options, and that this is best done using project specific code (perhaps as robot plugin?)

**Comment by sesuncedu** [comment]
Can you clarify "subject source"  and "target source"?

Also, when splitting by axiom type,  beware of Declaration.  RDF formats
require declarations for parsing,  so unless explicitly disabled, OWLAPI
will add any missing declarations back in (e.g. HasKey becomes ambiguous).

Declaration axioms are basically useless otherwise- although they do
provide a place to mistakenly put annotations (the annotations apply to the
axiom, not the entity), so they may require fixes to achieve true
uselessness.

[e.g The OWL Full/DL Gap in the Field
<http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf> 49-60
Nicolas Matentzoglu, Bijan Parsia.  ] (http://
<http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf>ceur-ws.org
<http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf>
/Vol-1265/owled2014_submission_9.pdf
<http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf>)

**Comment by cmungall** [comment]
I figured piggybacking off of the axiom annotation to rdf spec to define source/target.. but that may not be so simple

I mostly had subClassOf-SomeValuesFrom and equivalentTo-intersectionOf patterns in mind, but even within these subsets we need cover GCIs, and for intersections there would be multiple targets

A better idea would be to abandon `TS` and for `SS` specify this as being the ontology in which the axiom is declared (or rdfs:isDefinedBy)

We still need some suitably fragile rules for contracting the ontology IRIs such that they can be embedded in other IRIs. This feels like a project specific kind of rule. Perhaps `split` should be simplified, only by axiom type
