### ISSUE TITLE
Add option to extract command to stamp classes with rdfs:isDefinedBy

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#390]
If selected, each class in a generated module would have an isDefinedBy annotation to the URI of the source ontology, unless isDefinedBy is already present.

**Comment by balhoff** [comment]
It seems to me that for `extract` it would make more sense to have the subject be the extracted axiom rather than the class.

In some of my code I do have a utility that adds isDefinedBy annotations terms that have OBO-style IRIs to the canonical ontology IRI for that OBO namespace (much faster to query for them this way than filtering on IRI text).

**Comment by cmungall** [comment]
It would be good to support any combination of C+A.

A rough start at some conventions here:

- on the class means the URI is managed by the group. By default, they 
should be group that assert axioms with the class as subject
- on the axioms means the axiom is managed by the group. usually this is 
the same group that 'owns' the class URI, but in some cases axiom 
injection from outside is encouraged

Note that 'subject' doesn't make sense at the OWL level for some axiom 
types like DisjointClasses, EquivalentClasses between two named classes.

**Comment by rctauber** [comment]
We now have this feature with #392. Is this OK to close or does it require more discussion?

**Comment by cmungall** [comment]
Yes we can add new tickets for enhanced functionality later
