### ISSUE TITLE
--labels true option not recognised

### ISSUE THREAD

**Issue by mcourtot** [ontodev/robot#397]
```
C02XG3Q1JHD3:DUO courtot$ robot diff --left ./src/ontology/duo-edit.owl --right-iri http://purl.obolibrary.org/obo/duo.owl --output release_diff_2.txt --labels true

UNKNOWN ARG ERROR unknown command or option: --labels
```

from http://robot.obolibrary.org/diff: The output is in OWL Manchester syntax, but you can include entity labels with` --labels true.`

**Comment by jamesaoverton** [comment]
Sorry, the `--labels` option was added after the last ROBOT release. It will only be available if you build ROBOT yourself.

We're planning a new release soon that will include this (and all the other recent changes).

The underlying problem is that our docs can get ahead of our releases. The best solution is to release more often.

**Comment by cmungall** [comment]
Not sure of a good solution to this.

We could build the GH pages site off of a different branch from the one we develop on?

Or just annotate the docs with the version in which the feature was added?

**Comment by jamesaoverton** [comment]
In the short term, I intend to make more small releases, starting this week. Let's see if that solves the problem.

See #261 for previous discussion.

**Comment by mcourtot** [comment]
built it from source and --labels works just fine. thanks.
