### ISSUE TITLE
com.carrotsearch.hppcrt.BufferAllocationException: Not enough memory to allocate buffers to grow from 4194304 -> 8388608 elements

### ISSUE THREAD

**Issue by ginodeon** [ontodev/robot#420]
I have got 16GB RAM and 100 GB free disk space

When I run the robot (for example  "robot extract -i /files/ncbitaxon.owl -t http://purl.obolibrary.org/obo/NCBITaxon_31013 -o /files/ncbitaxon_bagridae.owl --method TOP"), I get following error:

com.carrotsearch.hppcrt.BufferAllocationException: Not enough memory to allocate buffers to grow from 4194304 -> 8388608 elements

Have you experienced the same? Thank you for your help

**Comment by rctauber** [comment]
Hi @ginodeon - thanks for bringing this up!

I'm not entirely sure where the `com.carrotsearch.hppcrt` library is coming from. Did you build the JAR from the source code or download it from [the release](https://github.com/ontodev/robot/releases/tag/v1.2.0)?

That said, NCBITaxon is a pretty big file and can cause some issues, such as `OutOfMemoryError`s. Since this looks like a memory issue, you can try increasing the max heap size and see if this helps:
```
ROBOT_JAVA_ARGS=-Xmx4g && \
  robot extract -i /files/ncbitaxon.owl \
  -t http://purl.obolibrary.org/obo/NCBITaxon_31013 \
  -o /files/ncbitaxon_bagridae.owl --method TOP
```

Even though your computer has 16GB, your default heap size for Java is probably only 1GB. You can set that `-Xmx4g` number to any size, e.g. `-Xmx8g`, depending on how much memory you might need.

**Comment by ginodeon** [comment]
Thank you very much!!

My robot has been built with docker.

I launched the following command and it worked!

sudo docker run -it --rm  -e ROBOT_JAVA_ARGS=-Xmx16G  -v $(pwd):/files robot extract -i /files/ncbitaxon.owl   -t http://purl.obolibrary.org/obo/NCBITaxon_31013   -o /files/ncbitaxon_bagridae2.owl --method TOP
