### ISSUE TITLE
Consider a way to circumvent unsafe certificates for ontology downloads

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#422]
It occasionally happens that a certificate of a download location is outdated or cannot be verified, which causes ROBOT to fail hard. This may be desirable (safety), but maybe causing sudden, unpredictable failures across ontology release pipelines using ROBOT. For example, PR recently moved from their FTP site to a space in the udel domain. This domain has an unsafe certificate. Which caused all pipelines importing PR to suddenly fail. Here is a simple example:

```
robot convert -vvv -I https://research.bioinformatics.udel.edu/PRO/data/current/pro_reasoned.owl -o pr.owl
```
(I replaced the purl with the udel redirect because Darren has already changed the purl back to the FTP for now)

I suggest making it possible to at least voluntarily circumvent unsafe certificates.

**Comment by jamesaoverton** [comment]
Thansk @matentzn. I understand the problem and why it's frustrating, and I appreciate the suggestion. But I'm uncomfortable with this solution for several reasons:

1. Ontology providers are responsible for providing their ontologies. This bad certificate problem will affect many tools and users, not just ROBOT. I think it needs to be fixed upstream.
2. There's an easy workaround, with many other advantages: use `curl` to fetch the ontology files, since it has every option you could desire, then run ROBOT locally.
3. To avoid this PR breakage, it sounds like you would have had to tell ROBOT to always ignore certificates for PR. So why not always ignore all certificates, since they might break something some time? I think that takes us in the wrong direction.
4. ROBOT relies on OWLAPI for loading functionality. I'm not aware of an OWLAPI option to ignore certificates (if I'm wrong, let me know), so we would have to implement another loading system for ROBOT. That's a very narrow solution to a wider problem.

In sum, we'd have to write a bunch of new code to provide a ROBOT-specific fix for a problem that should be fixed upstream, but is already easy to work around with `curl`.

**Comment by matentzn** [comment]
Fair enough! Thanks for that. I will forward the issue to Darren from PR.

**Comment by nataled** [comment]
Just to follow up on the certificate issue: turns out the certificate is valid. Short of moving PR to an insecure connection, there isn't anything we can do on our end. As I pointed out by email (which James did not see), this is not restricted to PR. I've had to revise a number of wget-based downloads to ignore the certificate check. I suspect there is some way to add certificate validation information locally, but wget doesn't provide that information so far as I can tell.
