### ISSUE TITLE
New command: shadow TBox in ABox

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#433]
It's standard practice to represent existentials as simple triples in triplestores, as querying the standard representation is awkward. Currently people do this in different ways.

We have proposed a standard "safe" way of doing this here: http://bit.ly/nc-ng

There is a lot of discussion in this doc, but it amounts to:

 * `X SubClassOf R some Y ==> X R Y`
 * Put these axioms in NG that is annotated with a triple that indicates the simple semantics is being used

Additionally we want two more NGs, one for direct and one for indirect:

https://github.com/NCI-Thesaurus/thesaurus-obo-edition/wiki/NCIt-graph-queries#property-relationships

We now have an easy way for materializing direct and indirect inferred axioms, including existentials:

https://github.com/ontodev/robot/issues/273#issuecomment-458954125

In theory it's not hard for someone to chain together a build pipeline for a triplestore using `construct` and `reason` and `annotate` commands.

But it would be good to have a standard pre-packaged way of doing this

Some of this overlaps the functionality of @balhoff's https://github.com/balhoff/blazegraph-runner

cc @dougli1sqrd @dosumis

**Comment by balhoff** [comment]
I think we have agreed that "relation graph" is a good name for this. Does this rise to the level of a new command? Should it be an option to the `materialize` command? This operation is related to that one but not the same (I expect to implement this using separate logic). One problem with `materialize` is that what it does is very specific, but I think many folks consider that to mean the broader operation of just storing inferences.

One possibility:

`robot materialize --reasoner ELK --input emr_example.obo --output-relation-graph emr_example_graph.ttl`

Notes:
- [The code I have for this](https://github.com/NCI-Thesaurus/ncit-utils/blob/master/src/main/scala/org/renci/ncit/MaterializePropertyExpressions.scala) is quite small and simple; I don't think it is useful for it to build on the approach used by the EMR (which is useful in its own way).
  - EMR injects all the property restrictions into the ontology and classifies them all at once. Can be faster for a small set of properties.
  - My code instead performs many queries. It streams the results out as RDF and so can use far less memory and scale up to hundreds of properties. This is particularly faster when using Whelk, which is much faster at answering DL queries and can answer these queries in parallel.
- I will move my code to a separate small project and update it to accept any OWL reasoner (it will still look for Whelk and use it slightly differently, since it can avoid some bottlenecks in OWL API that way).
  - I'll add Whelk as a reasoner option to ROBOT at the same time.
- If this is an option for the existing `materialize` command, how can the arguments be structured so that it avoids performing unnecessary work (e.g. bypassing the existing code if you are not going to output an OWL ontology with the someValuesFrom expressions injected)? This is a command line interface question.
- If we want a separate command, what is a good name for it? `materialize-relation-graph`?

**Comment by jamesaoverton** [comment]
I don't tend to use `materialize` but I'm fine with the proposed enhancements. For the name I prefer the simple verb `materialize` to `materialize-relation-graph`. Note that the `extract` command runs very different code for SLME (`ExtractOperation.java`) vs MIREOT (`MireotOperation.java`), and that could serve as a model for this. Also like `extract`, I think adding a `--mode` option to `materialize` (defaulting to the current behaviour) could be a good solution.

**Comment by balhoff** [comment]
Thanks @jamesaoverton that's very helpful.

**Comment by cmungall** [comment]
I'm responsible for some of the terminological confusion. Really, `materialize` is not so different from `reason`. The latter materializes entailed axioms. Originally just SubClassOf between named classes, but now other axioms. A separate command was created as the OWLAPI Reasoner API doesn't support the ability to easily find entailed axioms following the `X SubClassOf R some Y`(relational graph)  pattern despite this being one of the most useful inferences in multiple biological ontologies since the 90s... 

I think using materialize to also be used for doing a transform whereby RGs are shadowed as simple triples could be confusing.

One option could be a hyper-general `transform` command. Like the currently `extract` command, it could allow for different algorithms/methods. Arguably this is sneaking a whole different command subsystem in but I am not sure that is necessarily bad?

**Comment by jamesaoverton** [comment]
My only problem with a mode switch such as `transform --mode X --foo bar` is that different modes will want different options, and we have to tell the user which ones work where. This is already annoying for `extract`, because our MIREOT implementation allows several options that SLME does not, and SLME allows a couple that MIREOT does not.

Because of decisions I made long ago about chaining, I don't think we can just introduce a level of subcommands such as `robot transform relation-graph -i bar -o baz`.

That said, maybe a general `transform` is still the right choice for this.

I guess you don't like `shadow` as a command name, even though it's in the title of this issue?

**Comment by balhoff** [comment]
One thing I don't like about `transform` and `shadow` is that to me they imply a rendering of axioms stated in the ontology into a different form. The operation I am proposing is instead reasoner-based, and outputs all implied class relations `X SubClassOf R some Y`, regardless of how they were inferred from what's in the ontology. Does that bother anyone else?

**Comment by cmungall** [comment]
I agree, need to think about this a bit more

**Comment by cmungall** [comment]
I'm going to close this as this is probably outside the scope of ROBOT

Note that the original request (shadow tbox in abox) would be covered if we implemented an alternative OWL to RDF* mapping as proposed here:

https://douroucouli.wordpress.com/2019/07/11/proposed-strategy-for-semantics-in-rdf-and-property-graphs/

If there was a JVM implementation of this then robot could simply import this and treat it as format conversion.
