### ISSUE TITLE
Travis problems with oraclejdk8

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#505]
As of this morning, Travis switched us from Ubuntu Trusty to Ubuntu Xenial, which is causing the installation of `oraclejdk8` to fail and break all builds. Here's a failing build:

https://travis-ci.org/ontodev/robot/jobs/544719496#L1

This seems to be the relevant thread about the issue:

https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/16

The suggestions are switch to a newer JDK (such as 11) or use `dist: trusty`. I'm trying the latter here #504, and it seems to be working for now.

As for the former, we try to match ROBOT to Protege as much as possible. I think this is their main thread for upgrading from Oracle Java 8 to OpenJDK 11:

https://github.com/protegeproject/protege/issues/822

I haven't been paying much attention to the recent Java changes. Any thoughts?

**Comment by balhoff** [comment]
I've been sticking with Java 8 for a while, partly because it was required for previous versions of Scala. But Scala is fine with Java 11 now, and I'm thinking it's past time for me to go ahead and switch. It isn't totally clear to me but I think future use of Java 8 (for commercial purposes) requires a license (or something like that). In the past I always tried to move to the latest Java, but the whole 9-10-11 sequence has been kind of confusing.
