### ISSUE TITLE
Strange behaviour with FOODON import

### ISSUE THREAD

**Issue by pbuttigieg** [ontodev/robot#515]
@ddooley @cmungall 

Over at SDGIO, in https://github.com/SDG-InterfaceOntology/sdgio/pull/170, we're trying to import [nutrition-related claim or use](http://purl.obolibrary.org/obo/FOODON_03510065) using `robot extract`.

This class is under information content entity (after a few intermediates); however, on import, it gets orphaned: 

![image](https://user-images.githubusercontent.com/2276146/59792093-bab9bc00-92d3-11e9-9e38-f80b3f154fae.png)

We even imported it's parent in the hope that it would bridge the gap, but no luck. 

Not sure if this is an ontology issue or a ROBOT issue.

**Comment by jamesaoverton** [comment]
Ok. Please provide the exact command you are running.

**Comment by pbuttigieg** [comment]
We're running this target:
https://github.com/SDG-InterfaceOntology/sdgio/blob/issue-169/src/Makefile#L106-L109

referencing [this term index](https://github.com/SDG-InterfaceOntology/sdgio/blob/issue-169/src/imports/foodon_terms.txt) and generating [this owl file](https://github.com/SDG-InterfaceOntology/sdgio/blob/issue-169/src/imports/foodon_import.owl) for import.

Readout:

```
make imports/foodon_import.owl
Makefile:71: warning: overriding recipe for target '.PRECIOUS'
Makefile:60: warning: ignoring old recipe for target '.PRECIOUS'
owltools http://purl.obolibrary.org/obo/foodon.owl --remove-annotation-assertions -l -s -d --remove-axiom-annotations --remove-dangling-annotations --make-subset-by-properties -f BFO:0000050 BFO:0000051 RO:0002202 immediat/sdgio/src # make imports/foodon_import.owl
Makefile:71: warning: overriding recipe for target '.PRECIOUS'
Makefile:60: warning: ignoring old recipe for target '.PRECIOUS'
robot extract -i mirror/foodon.owl -T imports/foodon_terms.txt --method BOT -O http://purl.unep.org/sdg/imports/foodon_import.owl -o imports/foodon_import.owl
```

**Comment by cmungall** [comment]
This is an issue with the owltools step.. more shortly

**Comment by cmungall** [comment]
OK, this is not a robot issue but for completion purposes, here is the overall context.

In a lot of pipelines we massage the OWL file that is used to make the import using robot extract. This is often necessary because we often have poor modularization design in OBO and lots of reciprocal imports, and we don't want stale copies of the main ontology in the imports. Historically this massaging has had to be highly customized to the weird properties of each import. I haven't fully debugged what has happened here but I think it's something to do with the fact that some of the axioms being dropped are in the langual_imports rather than the main foodon.

It may be the case that we don't need to massage foodon before bringing into an sdgio import, if we do this should be done using `robot filter`. We can follow up on the linked ticket, just wanted to provide context

**Comment by ddooley** [comment]
Hmm.  If it is any help, there's always a foodon_merged.owl file that takes in all import axioms into one file.  However it sits in /src/ontology/ and gets subject to more updates than the FoodOn release versions.

**Comment by pbuttigieg** [comment]
Thanks @cmungall 
@ddooley we'd much prefer to stick with the release versions to avoid more weirdness down the line.

**Comment by pbuttigieg** [comment]
> We can follow up on the linked ticket, just wanted to provide context

Linked to this ticket?
