### ISSUE TITLE
'remove' based on language attributes

### ISSUE THREAD

**Issue by allysonlister** [ontodev/robot#571]
I would like to remove all rdfs:labels that have anything other than "anystring"@en, also preserving those rdfs:labels that have no language attribute set.

To try to get this started, I attempted to just remove those labels that have "anything"@zh as follows (a good test ontology for this is CLO at http://www.clo-ontology.org/ as it has multiple languages):

```
java -jar build/robot.jar  remove --input input.owl --term rdfs:label --select "rdfs:label=~'.*'@zh"  --output build/test.owl
```

However the above statement removes all labels whether or not they have a language set. I can't help feeling that I'm circling around the appropriate command, but I just can't see it. Please could I have some pointers?

Thanks :) Allyson

**Comment by jamesaoverton** [comment]
Hmm. It looks like we don't support selection by language tags in `remove`/`filter`. We do support selection with datatypes (`^^`), so that's an oversight that we should fix. @beckyjackson Can you please add this?

The `=~` matching rule you're trying to use will only match the content of an annotation. The language information is stored separately, so that won't do what you want.

My best suggestion with current ROBOT features is to use SPARQL UPDATE:

```
java -jar build/robot.jar query --input input.owl --update delete-en.ru  --output build/test.owl
```

where `delete-en.ru` is a file with this content:

```
DELETE { ?s ?p ?o }
WHERE { ?s ?p ?o; FILTER(lang(?o) = "en") }
```

That should work, but I haven't tested it. More documentation here: http://robot.obolibrary.org/query#sparql-update

**Comment by allysonlister** [comment]
Thanks very much. Will keep an eye out on the remove/filter command. In the meantime, your sparql update suggestion worked perfectly. For reference, here is the .ru file I used in the end:

```sparql
# Delete any rdfs:label where the language is set to 'zh'
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE {
  ?class rdfs:label ?display_name
}
WHERE {
  ?class rdf:type owl:Class.
  ?class rdfs:label ?display_name
  FILTER(lang(?display_name) = "zh")
}
```

**Comment by allysonlister** [comment]
Thanks very much! And yes, the SPARQL UPDATE worked great for me - I included the code above for reference. I'm happy for you to close the ticket - just didn't want to do it myself in case you were waiting for something internally first.

Thanks again for all your help :) Allyson

**Comment by beckyjackson** [comment]
Great, thank you!

**Comment by matentzn** [comment]
Just came across the same, wanting to remove all labels (all annotations for that matter) that were Chinese. Using sparql as well, thanks all.
