### ISSUE TITLE
Feature requests for semantic diff

### ISSUE THREAD

**Issue by drseb** [ontodev/robot#586]
Hi,

I just used semantic diff for HPO. I have some request that could make it more useful for HPO.
Can we give names to each ontology given to the diff? Right now the result reads like this 

> ... axioms in Ontology 1 but not in Ontology 2:

It could be more intuitive if I could name the first ontology new and the other one old or something like this.

The next issue is that the diff contains many changes in external/imported ontologies. Can you add a filter that can be used to focus the diff on a particular subset, e.g. only axioms that contain an IRI that contains "HP"?

Thanks,
Seb

**Comment by matentzn** [comment]
I agree it would be nice to have the diff more configurable, i also get always confused about Ontology 1 and Ontology 2. Maybe we can have the actual ontology iris/filenames there instead.. In the absence of a parameter for excluding imported ontologies, I would recommend to implement two ROBOT chains, something like this (untested):

```
o1.owl: o1-src.owl
   robot remove -i $< --select imports --trim false  -o $@

o2.owl: o2-src.owl
   robot remove -i $< --select imports --trim false  -o $@

robot_diff.txt: o1.owl o2.owl
     robot diff --left o1.owl --right o2.owl -o $@
```

**Comment by balhoff** [comment]
@drseb you may like the HTML or Markdown outputs better. Besides being more readable, they call the ontologies "Old" and "New", although that kind of seems problematic. We should probably just call them "left" and "right", since that's the command line parameters (and I think your order of old and new is the opposite of the one used!).

The diff does not include anything from imported ontologies. I guess you're seeing axioms that have been copied into the file you're looking at. I think it's important that the diff represent exactly the axioms in the ontology files it's given (especially so you can see problems like you're mentioning). In my opinion any filtering should be done using other robot functionality before running diff. For HPO it might be useful to compare `hpo-base` rather than the full ontology.

**Comment by matentzn** [comment]
diffing the base is exactly the best thing to do! in any case, my pipeline pattern here applies to all kinds of situations, for example where you want to only compare the subclass relations in the diff (use robot filter) or some other specific set. But yes, for your use case diffing base is the best idea. Is this something that would make sense as part of the normal odk Workflows? Diffing the base to the latest release and providing a nice markdown summary along with it?

**Comment by cmungall** [comment]
What's the status of this ticket? It seems using base solves many problems?

We do need to align terminology:

 - command line says left/right
 - plain output says 1/2
 - md output says old/new

Not ideal but is this a major problem? Too late to change command line now but maybe we could standardize output on old/new?

**Comment by drseb** [comment]
HPO is now using its own implementation. See https://github.com/obophenotype/human-phenotype-ontology/tree/master/src/ontology/reports

I would suggest to robot to use the old/new naming scheme or at least aim for consistency.

**Comment by balhoff** [comment]
I would like to standardize on left/right: https://github.com/balhoff/owl-diff/issues/6

I opened that issue a while back but haven't gotten to it.

**Comment by matentzn** [comment]
Left right works for me; old new has the appeal that for the most important use cases (comparison of two successive versions), I have a more meaningful label that I can map immediately in my mind to the corresponding file, while left right is a bit.. uuu which one was left again? But it is more generic terminology wise, not restricted to successive versions (e.g. it applies to variants as well). So yeah, I think left right makes sense, especially since the parameters in robot are called left-right as well.

**Comment by drseb** [comment]
My vote is for old/new, but left/right seems okay-ish 😋

**Comment by balhoff** [comment]
@jamesaoverton do you consider the "Ontology 1" and "Ontology 2" text in the plain text diff output to be an "API" that should not be changed? Or can I update that to use "left" and "right"? I've changed the Markdown and HTML outputs in #729.

**Comment by jamesaoverton** [comment]
@balhoff Let's use left/right consistently throughout, even though it means a small change in the plain text diff output. Thanks!

**Comment by balhoff** [comment]
Okay, I updated the PR to include that also.
