### ISSUE TITLE
Allow per-column control for named/anonymous in export

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#682]
The new `export` command has a `--exclude-anonymous` option that applies to the whole sheet. We need to allow per-column overrides the global option.

This only applies to logical columns. Two options that occur to me are:

1. add a "Named" variant to each local column type: "Named SubClassOf"
2. add a "named" option to the `[options]` for the column: "SubClassOf [ID named]"

Other suggestions?

**Comment by beckyjackson** [comment]
I think I like `Named SubClassOf` better, although I'm worried about how this might interact with properties (if for some reason a property starts with "named"). The reason I don't like `[ID named]` is because the contents of the square brackets are how the entities are rendered, not the types of entities...

A third option could be listing changing the `--exclude-anonymous` to work something like this:
- `--exclude-anonymous <true|false>` operates over entire sheet
- `--exclude-anonymous <columns>` allows you to input a set of columns (in any order, does not have to match the header order, but the names must match) to exclude anonymous from

So you could:
```
robot export \
  --header "ID|LABEL|SubClassOf [ID]|part of [ID]" \
  --exclude-anonymous "SubClassOf [ID]|part of [ID]"
```

Or we could have another option for this `--exclude-anonymous-from` but that seems a bit verbose.

**Comment by jamesaoverton** [comment]
I don't like the third option. Too repetitive.

If the square brackets mean "override" or "force" then I think the second option makes good sense.

**Comment by beckyjackson** [comment]
OK, that makes sense when you put it that way. I'll implement it as the second option.

**Comment by cmungall** [comment]
This seems reasonable.

I assume `Named` only has an effect if we say `--exclude-anonymous false`.

The other way to do this is to flip it around. Use a keyword such as `Expression` (meaning: permit named entities or expressions), which is only applied if `--exclude-anonymous true`.

This reflects my bias: I may want to export named fillers for existentials for multiple properties, but also include an informative logical definition field. I suspect this may be the case for Janna and others too.

**Comment by cmungall** [comment]
Now I think about it, equivalence axioms serve a different pragmatic function. It might be useful to have two separate columns:

 * Named Equivalents
 * Logical definitions (anon equivalents)

So how about this:

 - a keyword `Anonymous` that *only* shows anonymous
 - a keyword `Named` that *only* shows named
 - a keyword like `Any` or `Expression` that shows all in the same column
 - If no keywords are specified then behavior is entirely driven by `--exclude-anonymous`
 - The keywords always override `--exclude-anonymous` (on a per-column basis)

This is a bit more complex but, it *may* be a bit more future proof (by allowing more fine-grained control) and serve more use cases. And most people can get by without even considering keywords, just using `--exclude-anonymous` (if that)

**Comment by cmungall** [comment]
> I'm worried about how this might interact with properties (if for some reason a property starts with "named")

Lets be safe. Select an ascii symbol as a prefix? Something that doesn't end up looking like obfuscated perl. E.g. `:NAMED`

**Comment by jamesaoverton** [comment]
If we use keywords inside square brackets (my preference) there won't conflicts.

Here are some small revisions on what Chris is proposing.

We have the `--entity-format` option for rendering entities, which accepts one of (case insensitive): NAME, ID, IRI, LABEL. The default is NAME. Then we can override per-column with square brackets, e.g. `SubClassOf [IRI]`. Let's copy that pattern.

1. drop `--exclude-anonymous`
2. replace it with `--entity-select` (suggestions for a better name are welcome!) which accepts one of (case insensitive): ANY, NAMED, ANON, ANONYMOUS. I still like ANY as the default, but since we're breaking things now we could change that. Then we can override per-column, e.g. `SubClassOf [named]`.
3. handle interactions: anonymous stuff won't have an ID or IRI, and almost never has a LABEL, so
    - ID, IRI, LABEL implies NAMED
    - warn on bad combinations like `[anon ID]` and `--entity-format ID --entity-select ANON`

**Comment by jannahastings** [comment]
I like this proposal, thanks a lot! 

Just taking a step back, now that I think about it more, for my use cases, being able to have just "simple" named entities (e.g. parent classes) in some columns, while still allowing full logical axioms (e.g. equivalent class expressions) in other columns, is very important. The general motivation behind this requirement is that the people I work with who are interacting with ontologies via this sort of exported file see named classes as very different sorts of thing to axioms. The named classes and the relationships between the named classes are part of what can be thought of as a _"simplified graph view"_ of the ontology content, while the logical axioms are of course a _"full logical expressivity"_ view of the ontology content. I would want to be able to show the graph view of the ontology in the form of the named classes and their relationships, which is well served by restricting column values to NAMED only for the SubClassOf and object property type columns. However, I would also want the information in the export to be *complete* in some sense, which means having a way to include any additional content from the "logical view" (where it is present) in the same export, i.e. in different columns, without unnecessary redundancies. 

This raises a further question about the representation of object property targets as named-only vs. as full axioms. I understand that columns with an object property header currently get the object property target as the column value, regardless of whether the relevant object property restriction is existential or universal. For example, if I have A 'has part' some B in the ontology, and I put the header "has part" in the export, then I get B as the value in the cell. This makes perfect sense for the "graph view" part of the export. However, OWL allows additional logical complexity to be captured in object property expressions, for example, we may want to capture a value restriction with a nested OR expression (e.g. 'has part' only ('carbon atom' or 'hydrogen atom') ). In the latter case, I think it makes sense to have the whole expression including the quantification as the output, if the header is 'has part [ANON]', not just the target (carbon or hydrogen). So the distinction is not just named or not named, from this perspective, but simplified (to a graph view) or with the full OWL complexity?

Minor points:

I agree that --entity-select ANY should remain the default. 

One comment/question about the "bad combinations" (point 3 in James's comment above): while it is true that the columns of type ID, IRI and LABEL would not have axioms in them, I think the combination of --entity-format ID with --entity-select ANON is not necessarily bad, because *inside* the axioms there are still embedded labels or embedded IDs pointing to other entities. --> If I do the current export with --entity-format ID at the moment, without exclude-anonymous=true, the output I get has embedded IDs in axioms.

**Comment by jamesaoverton** [comment]
@beckyjackson has an implementation of this to review. Please try it out:

- docs https://github.com/ontodev/robot/blob/export-named/docs/export.md#rendering-cell-values
- JAR https://build.obolibrary.io/job/ontodev/job/robot/job/export-named/lastSuccessfulBuild/artifact/bin/robot.jar

**Comment by jannahastings** [comment]
This is great, I really like the design! It's going to be so useful.

But when I run it, I am not sure it is doing quite what I would expect?

here is one of the rows of output from my test scenario exporting ChEBI to CSV (The 'equivalent class' expression is not real, I just added something to test this now, but the rest of the content is from ChEBI as is)

robot export --input chebi.owl --header "ID|LABEL|SubClass Of [NAMED]|SubClass Of [ANON]|Equivalent Class|has part [NAMED]|has part [ANON]|has role" --export chebi.csv

CHEBI:15377,water,_'has role' some 'Escherichia coli metabolite'|'has role' some 'Saccharomyces cerevisiae metabolite'|'has role' some 'amphiprotic solvent'|'has role' some 'greenhouse gas'|'has role' some 'human metabolite'|'has role' some 'mouse metabolite'|'is conjugate acid of' some hydroxide|'is conjugate base of' some oxonium_|inorganic hydroxy compound|mononuclear parent hydride|oxygen hydride,'has role' some 'Escherichia coli metabolite'|'has role' some 'Saccharomyces cerevisiae metabolite'|'has role' some 'amphiprotic solvent'|'has role' some 'greenhouse gas'|'has role' some 'human metabolite'|'has role' some 'mouse metabolite'|'is conjugate acid of' some hydroxide|'is conjugate base of' some oxonium,('has part' some 'oxygen atom') and ('has part' some 'hydrogen atom'),hydrogen atom|oxygen atom,,Escherichia coli metabolite|Saccharomyces cerevisiae metabolite|amphiprotic solvent|greenhouse gas|human metabolite|mouse metabolite

The bit in italics above shows expression-like superclasses that I would not have expected to appear in the SubClassOf [NAMED] column.  

Just another small point: in the documentation, the link in "Any prefix used _must be defined_." for (I guess) explaining how to specify prefixes doesn't seem to work -- it gives "Page not found".

**Comment by jamesaoverton** [comment]
Thanks @jannahastings. I can confirm that incorrect behaviour: NAMED columns are also including ANON stuff.

@beckyjackson Please add a test with `--header "ID|LABEL|SubClass Of [NAMED]|SubClass Of [ANON]|SubClass Of [ANY]"`, which should help track down this problem.

**Comment by beckyjackson** [comment]
Thanks for the catch! It looks like the `NAMED` tag was being caught by regex as `NAME`. I've fixed this and updated the PR.

**Comment by jannahastings** [comment]
Works for me now :-)

**Comment by cmungall** [comment]
Not sure if there is a bug or if I just don't understand the docs.

I'm trying to force a column to be populated only by anon classes.

For example, say I want one column for named superclasses and a separate column for anons, e.g.:

```
cob.tsv: cob.owl
	$(ROBOT) export -i $< --entity-select NAMED -c "ID|ID [LABEL]|definition|subClassOf [ID]|subClassOf [LABEL]|subClassOf [ID ANON]|subClassOf [LABEL ANON]" -e $@
```

When I do this, c4 and c6 are identical, and only named

I'm trying to be more explicit here:

```
cob.tsv: cob.owl
	$(ROBOT) export -i $<  -c "ID|ID [LABEL]|definition|subClassOf [ID NAMED]|subClassOf [LABEL NAMED]|subClassOf [ID ANON]|subClassOf [LABEL ANON]" -e $@
```

c6 contains a mix of named and anon
