### ISSUE TITLE
Error running a fresh download on windows

### ISSUE THREAD

**Issue by kMutagene** [ontodev/robot#698]
Hi there,

I followed the setup instructions from the docs:

> Windows
> Download the robot.jar file from the latest release.
> Save the ROBOT batch script.
> OR enter echo java -jar %~dp0robot.jar %* > robot.bat in the same directory as robot.jar to create the batch script.
> Put both files on your system PATH in the same directory.
> this could be C:\Windows\
> OR update your PATH to include the new directory.
> Make sure robot.bat is executable by running icacls robot.bat /grant Users:RX /T from the command prompt in the same directory.
> Now you should be able to run ROBOT from a command line:

Doing this results in the following error calling `robot help` : 

```
PS C:\Users\kevin\Desktop\robot> robot help

C:\Users\kevin\Desktop\robot>■j
'■j' is not recognized as an internal or external command,
operable program or batch file.
```

Running the command `java -jar robot.jar help` works fine though.

**Comment by jamesaoverton** [comment]
Thanks for the excellent report @kMutagene. What version of Windows are you using?

Unfortunately I don't have a Windows machine to test on. Can anyone else help with this? @ontodev/robot-team

**Comment by matentzn** [comment]
I followed [these steps](http://robot.obolibrary.org/) from the documentation:

1. Download the bat file. typical error: its saved as a `robot.bat.txt` file instead of `robot.bat`
2. Download the robot jar (latest release)
3. In CMD, run `java -version` to confirm that I have at least Java 8 installed
4. Then go (`cd mydir`) to the directory which has both the `robot.bat` file and the `robot.jar` file. 
5. Then run `robot --version` 

Works fine for me. 

Your problem sounds like a copy-paste error when downloading the bat file. I recommend going to the [documentation](http://robot.obolibrary.org/) and using `right-click -> safe as` to safe the bat file in the correct directory.

**Comment by kMutagene** [comment]
@matentzn That works, thanks! I think the reason is that the command listed in the docs

> Save the ROBOT batch script.
> OR enter echo java -jar %~dp0robot.jar %* > robot.bat in the same directory as robot.jar to create the batch script.


uses the wrong encoding for the file. Seems like powershell saves files by the `>` alias as UTF16. So users either have to make sure that they change their default parameter for text encoding or change the command to 

`echo "java %ROBOT_JAVA_ARGS% -jar %~dr0robot.jar %*" | out-file robot.bat -encoding utf8`

which worked for me.

**Comment by matentzn** [comment]
Cheers that makes a lot of sense. Maybe the docs should be updated to that end!
