### ISSUE TITLE
prefixes not working with robot export

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#721]
I tried running this on go.owl:

`robot export -i go.owl --header "ID|LABEL|IAO:0000115|oboInOwl:hasOBONamespace" --add-prefix "IAO: http://purl.obolibrary.org/obo/IAO_" --add-prefix "oboInOwl: http://www.geneontology.org/formats/oboInOwl#" --export table.tsv`

I don't get any output for `IAO:0000115` or `oboInOwl:hasOBONamespace`. If I use the labels for those properties, I do. Am I doing something wrong?

**Comment by beckyjackson** [comment]
Hi @balhoff - thanks for reporting this. I'll take a look and see what's going on.

**Comment by beckyjackson** [comment]
So, oddly enough, when you use the CURIE instead of the IRI, the IRI objects for the same annotation properties are not equivalent. Why? I'm not sure. But, we can get around this by comparing the IRI strings instead of the IRI objects from OWLAPI.

I opened a PR for this and you can test out the JAR: https://build.obolibrary.io/job/ontodev/job/robot/job/721-fix/lastSuccessfulBuild/artifact/bin/robot.jar

**Comment by balhoff** [comment]
> you don't need to specify these prefixes with --add-prefix because the issue wasn't the missing prefixes, it was in the export method

Thanks! I thought those ought to be known—that explains it.

**Comment by jamesaoverton** [comment]
So we have a fix in #722. @balhoff have you tested that?

Is there a workaround, or do we need a 1.7.1 release with the fix?

**Comment by balhoff** [comment]
@jamesaoverton I tested the fix and it worked for me. The workaround I have now is to use the labels for the two properties I needed, so it is not urgent.
