### ISSUE TITLE
allow 2-arg form for diff, instead of --left and --right options

### ISSUE THREAD

**Issue by jclerman** [ontodev/robot#781]
When using `robot diff`, one must specify the "old" and "new" ontologies using `--left` and `--right` (or the similar options with `-iri` extensions).  It would be nice to be able to skip typing of those two options - after all, the diff operation, by definition, always operates on two data-sources, and calculates the difference.  Would it be possible to implement a "shorthand" way to call diff, treating the first two robot arguments after the `diff` subcommand as the "old" and "new" items to compare?  For example, instead of 
  `robot diff --left old.owl --right new.owl` 
we could just type 
  `robot diff old.owl new.owl`.

As a bonus (maybe this part should be its own ticket), it should be possible to get rid of the two `--{left/right}-iri` options, instead detecting that an argument to `--{left/right}` is a fully-qualified IRI and treating it as such.

**Comment by jamesaoverton** [comment]
Thank you for the proposal. It makes perfect sense. Unfortunately this behaviour is embedded deep in the design of the ROBOT command line interface, and can't be changed.

When I designed ROBOT five years ago, it was critical that we could run chains of commands, like a Unix pipeline. Since it wasn't feasible to simply pass ontologies as streams of text, I decided to have a single ROBOT process execute a series of commands, passing data along with a CommandState object. For the command-line interface, I decided to use a feature of the Apache Commons CLI parser called [`stopAtNonOption`](https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/CommandLineParser.html#parse(org.apache.commons.cli.Options,java.lang.String%5B%5D,boolean)). So the command-line parser reads arguments until it sees a non-option, then runs one command. It keeps reading more arguments until it sees another non-option, and runs the next command. In other words, each non-option must be the name of the command to run, and all the options between are passed as to that command. In yet more other words, ROBOT command names are used as the separators between chains of commands, and thus everything that's not the name of a command must be specified as an option, with an option flag).

So we could have something like `robot diff --auto "http://purl.obolibrary.org/obo/foo.owl" foo.owl`, but to my mind that's not a whole lot better than the current behaviour.

This design works well enough, but I was never entirely happy with it. This issue has more information and an alternative design that we did not pursue: #62. Now it's too late to change.

I hope that explanation is helpful. Thanks again for submitting this issue, and sorry that we can't implement your proposal.

**Comment by matentzn** [comment]
One thing I do to achieve what you are doing is using custom commands in .bash_profile or zsh_profile like this:

```
rdiff() {
    robot diff --left "$1" --right "$2" -o "$3"
}
```

And then I can run this:

```
rdiff envo.owl envo.ofn envodiff.txt
```

**Comment by jclerman** [comment]
Thanks @jamesaoverton for the explanation and @matentzn for the workaround suggestion.  I do wonder about the 2nd part of my request (merging `--left-iri` and `--right-iri` into `--left` and `--right` respectively), but admittedly that wasn't the main focus of my request.

I think this issue can probably be closed with a tag like WontFix, given that #62 is closed.

**Comment by matentzn** [comment]
I would support that a bit -maybe not deprecate left-iri, but yeah, would you be opposed James to do a try catch trying to build a url and redirect to file only if that fails?

**Comment by jamesaoverton** [comment]
Thanks @jclerman. If someone makes a PR for your narrower proposal, and it's backwards compatible, then I'll consider merging it. I'm worried that this will add complexity to an already annoyingly complex part of ROBOT, without a big win in terms of usability. If you'd like to discuss the narrower proposal further, please open a new issue and link to this.

We appreciate your suggestions. I always hate saying "no" to perfectly reasonable requests, but the thing I hate most is breaking other people's code that depends on our code.
