### ISSUE TITLE
Switch to GitHub Actions for testing, and ideally for compiled JARs

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#800]
My ontodev org has already blown through 75% of our free Travis credits. I like GitHub Actions better than Travis, so let's plan to migrate to GitHub Actions.

We have also relied on build.obolibrary.io Jenkins for JARs from development branches. It would be better to tell GitHub Actions to upload those JARs somewhere.

**Comment by beckyjackson** [comment]
What are you thinking for the JAR hosting? Something like an AWS S3 bucket?

**Comment by balhoff** [comment]
@beckyjackson you could look at the artifact posting built into GitHub actions. Here is an example I'm using just to share files between jobs at GO:

https://github.com/geneontology/go-ontology/blob/135f67ae52668f239986aba4a49856bc61d6cd77/.github/workflows/inference_diff.yml#L36-L41

**Comment by beckyjackson** [comment]
Thanks @balhoff - where does this get hosted? Is there a link we can provide to people from which they can download the JAR?

**Comment by balhoff** [comment]
Here are more docs: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

This is an example from a GO run:

https://github.com/geneontology/go-ontology/actions/runs/504426753

Two are expired because I set a very short lifetime for them. The diff.md file is downloadable. But the URL is a little opaque. And I think the result is a zipped folder. So not sure if it will meet your needs or not.
