### ISSUE TITLE
Robot export header 'type' doesn't work

### ISSUE THREAD

**Issue by zhengj2007** [ontodev/robot#833]
I used following command for exporting VEuPathDB ontology:

robot export --input eupath.owl \
  --header "ID|LABEL|Type|SubClass Of [NAMED]" \
  --include "classes individuals properties" \
  --export eupath_terms.csv

The 'Type' column is empty. 

The command can retrieve Type information from other OBO Foundry ontologies, such as OBI, IAO. I used the SPARQL query to retrieve entity type of VEuPathDB ontology terms. It worked. 

The VEuPathDB ontology is available on http://purl.obolibrary.org/obo/eupath.owl

**Comment by jamesaoverton** [comment]
I could reproduce this. @beckyjackson please take a look when you get a chance.

**Comment by beckyjackson** [comment]
The root of this problem is that the `rdf:type` property is declared as an `owl:AnnotationProperty` in http://purl.obolibrary.org/obo/eupath.owl (line 759). `export` is attempting to look for any annotations using this as the annotation property, but there are none. I think, generally, there isn't usually a declaration for `rdf:type`.

If I remove line 759, this returns the expected result.

@jamesaoverton I'm wondering if I should make some sort of override to say that even if `rdf:type` is declared as something else, we ignore that declaration?

**Comment by jamesaoverton** [comment]
For this purpose at least, I agree that we should ignore declarations on `rdf:type`.

**Comment by jamesaoverton** [comment]
@zhengj2007 To be clear: VEuPathDB should not be asserting that `rdf:type` is an OWL Annotation Property. That could lead to unexpected behaviour in many tools, not just ROBOT.
