### ISSUE TITLE
Add check to detect http://org.semanticweb.owlapi/error#

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#878]
The OWLAPI will sometimes silently turn RDF into http://org.semanticweb.owlapi/error#Error1, Error2, etc nodes if it can't handle it.

There may be some strict mode in the owlapi that we can expose via robot commands? That would be another ticket. For now I would like to just flag all cases in all ontologies (whether made by robot or not) that have these.

I think we should also consider this an OBO principle failure for http://obofoundry.org/principles/fp-002-format.html

Some examples:

https://bioportal.bioontology.org/search?utf8=%E2%9C%93&query=Error1&button=

**Comment by matentzn** [comment]
@ignazio1977 Is there a way to achieve this with the OWL API? I mean without searching the ontology for the ERROR IRI pattern and throwing an exception?

**Comment by ignazio1977** [comment]
@matentzn Yeah those IRIs are generated when the input is missing triples (typically a restriction without a type).
If the parsing is set to strict (PARSE_WITH_STRICT_CONFIGURATION option in ConfigurationOptions) an exception is thrown, but strict parsing is not specific to this error - other errors which the API usually tries to repair will also cause exceptions to bubble up.
Otherwise, the logging will contain a message about the error, so that could be used to detect problems in batches of input files, I guess.

**Comment by matentzn** [comment]
The general case @ignazio1977 describes, ROBOT already supports: http://robot.obolibrary.org/global#strict-parsing

@cmungall does this cover your situation, or do we need more fine-grained control for this ticket here?

**Comment by matentzn** [comment]
Lets assume the strict mode covers the situation described.

**Comment by cmungall** [comment]
Unfortunately strict mode is too strict, it flags many things that are common that are properly repaired by the OWLAPI (perhaps this could be considered over-postelian of the owlapi and these rdf files should be considered buggy, but here we are). For example, undeclared predicates.
