### ISSUE TITLE
-I / --input-iri ignored

### ISSUE THREAD

**Issue by stuckyb** [ontodev/robot#90]
When the "extract" command is used, if a source ontology is provided via the -I / --input-iri option, robot throws a java.lang.IllegalArgumentException with the message "An input ontology must be specified".  I haven't tested whether this problem also occurs with other commands.

**Comment by cmungall** [comment]
This may be a dupe with #83

Check the ontology syntax is valid

**Comment by stuckyb** [comment]
I don't think it is a duplicate of #83.  In the case I describe, a perfectly valid IRI is provided, but robot simply ignores it and claims that no input ontology was specified.  In other words, robot doesn't even try to parse the ontology.

**Comment by jamesaoverton** [comment]
Thanks for the report. You're right, `--input-iri` isn't implemented for any of the commands. I think I stopped sort because I wanted to be consistent with how catalog files are used: ROBOT looks for them automatically when a local input file is used, but that doesn't make as much sense for remote files. Then I forgot to remove the option from the commands.

If it worked, would `--input-iri` be useful to you? Or would it be just as easy to download and work with local files?

**Comment by stuckyb** [comment]
For my current use case, it doesn't matter much to me either way.  Just removing the option would certainly be the easiest way to resolve this issue for now, and the feature could always be reconsidered for a later release.

**Comment by jamesaoverton** [comment]
Fixed by #220
