### ISSUE TITLE
How to deal with local onthology import

### ISSUE THREAD

**Issue by 4rcadiaN** [ontodev/robot#957]
Hello everyone,

I hope you had a nice christmas.
I hope you can help me with my problem: I am currently trying to use robot to do automated reasoning on automatically created ontologies but I am running into a problem. My generated ontologies have imports that are stored in files locally on my pc with IRIs like "urn://test" or "http://test.com/xxx". When I try to do reasoning on the ontologies robot tries to resolve these imports (by my understanding) by looking for them online but fails to do so because either there is no onthology available under that import link or for the urn:// imports there is no "appropriate factory" to load the ontology:

`INFO  Notice: root element does not have an xml:base. Relative IRIs will be resolved against inputstream:ontology1`
`INFO  Malformed URL: unknown protocol: urn`
`java.net.MalformedURLException: unknown protocol: urn`
`Could not find an appropriate factory to load ontology from ontology document: <urn://test>`

My question is now: How can I deal with local imports? I want that robots resolves the imports with the local files stored on my pc. Is there a way to tell robot this?

**Comment by jamesaoverton** [comment]
This is possible with a "catalog" file. When you specify an ontology file as an `--input`, ROBOT will look in that same directory for a file called `catalog.xml` (actually the first file it find starting with `catalog` and ending with `.xml`). It will read that file and use it to override import paths, usually by loading from a local file rather than a remote URL. 

Here are some examples:

- <https://github.com/ontodev/robot/blob/master/docs/examples/catalog.xml>
- <https://github.com/obi-ontology/obi/blob/master/src/ontology/catalog-v001.xml>

A few notes:

- Catalog files are a feature of OWLAPI, which ROBOT calls [like this](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L412)
- Protege will generate a catalog file when you use its Import Wizard: <https://protegewiki.stanford.edu/wiki/Importing_Ontologies_in_P41>
- When you use `--input-iri` ROBOT cannot automatically find the catalog file, but you can use specify it using [`--catalog`](http://robot.obolibrary.org/global#xml-catalogs).

**Comment by jamesaoverton** [comment]
Actually, a simpler option that might work just as well for your use case is to merge all your files into a single `merged.owl` file before reasoning, using [`robot merge`](http://robot.obolibrary.org/merge).

**Comment by jamesaoverton** [comment]
Hopefully you got this working, so I'll close.

**Comment by 4rcadiaN** [comment]
Yes using the merge function I got it working :).
