### ISSUE TITLE
new command: `expand`

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#963]
I would like to add an `expand` command to ROBOT. This would be used to apply "macro" expansions to generate axioms, primarily from annotation property assertions, although this can be pretty open-ended. Initially `expand` will support applying SPARQL CONSTRUCT queries to generate content. The command could be later extended with options for other systems. I will request an annotation property in OMO, which would link other annotation properties to SPARQL CONSTRUCT literal strings. Example:

```turtle
RO:never_in_taxon OMO:defined_by_construct """
   CONSTRUCT { 
      ?x owl:disjointWith [ 
         a owl:Restriction; 
         owl:onProperty RO:in_taxon; 
         owl:someValuesFrom ?y 
      ]
   } WHERE { 
      ?x RO:never_in_taxon ?y 
   }""" .
```

Running expand would apply all such CONSTRUCT values found in the imports chain to the current ontology and imports.

**Comment by balhoff** [comment]
Right now these kinds of expansions are being done in a variety of inconsistent ways across ontologies (owltools, CONSTRUCT, dosdp-tools, etc.). This would help with consistency. I'm hoping to also provide a way to perform these expansions when reasoning in Protégé.

**Comment by jamesaoverton** [comment]
I think this is a good idea, and ROBOT would be a good home.

I have a couple of thoughts (not objections, just thoughts):

In my mind, the main drawback to "shortcut relations" is consistency of representation. If the shortcuts are expanded in foo.owl but not expanded in bar.owl, then you need two different queries. If you aren't sure whether whether the shortcuts have been expanded in bar.owl then you need to run an expensive CONSTRUCT to make sure.

When I worked on shortcut relations in the past, I got hung up on making them reversible: supporting a 'contract' operation that would match the expanded pattern and generate the shortcut pattern. A one-way 'expand' should be straightforward, but two-way 'expand'/'contract' was much harder. I tired to express these reversible expansions concisely, and got stuck. 

So I think it would be good to decide up front whether 'contract' is in scope or not. "Out of scope" is a perfectly good decision.

A more pragmatic solution to mixed representations might be to add metadata indicating that 'expand' has been run. We've discussed this more generally since #6 but haven't implemented it.

**Comment by jamesaoverton** [comment]
One more thought: It would be very nice to be sure (or ensure) that these expansions are associative (i.e. sequence of application does not matter).

**Comment by balhoff** [comment]
> One more thought: It would be very nice to be sure (or ensure) that these expansions are associative (i.e. sequence of application does not matter).

I agree. For the basic macro system I envision here, the CONSTRUCTs would all be applied to the original ontology and not allowed to interact. I also imagined supporting a forward-chaining rule engine as an alternative. Those rules would interact but order wouldn't matter. That's just speculative for now though.

**Comment by balhoff** [comment]
Personally I don't think contraction is in scope. The application I see for these is representing cumbersome logic in a more editor-friendly way.
