### ISSUE TITLE
Cant get ROBOT materialize to work

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#985]
Usually I am on the answering end of this, but I have been battling with this issue for weeks now and cant get it to work.

I have this class in MP:

![image](https://user-images.githubusercontent.com/7070631/162171384-0243e07e-2d88-422e-ad0d-0c214db65fba.png)

cerebral blood vessel is defined like:

![image](https://user-images.githubusercontent.com/7070631/162171506-ed596cc0-d1bc-479d-8e04-142107562395.png)

`phenotype is associated with entity` is defined like:

![image](https://user-images.githubusercontent.com/7070631/162171630-f4927cfd-1b17-43aa-8ce3-3738ff0435b0.png)

How can I materialise:

```
"cerebral vascular congestion" subClassOf "phenotype is associated with entity" some "cerebellum"
```

Here is the a not working example:

```
robot materialize -I https://www.dropbox.com/s/1zohgs9j8s54c3t/mp-test.owl?dl=0 --term http://purl.obolibrary.org/obo/UPHENO_0000003 -o mp-test-mat.owl
robot diff --left mp-test.owl --right mp-test-mat.owl -o diff.txt
```

Any pointers ideas appreciated, because I have tried everything now to understand this. (Note that `diff.txt` includes some strange differences that also don't make sense, I would have expected these from `reason`, but not `materialize`, other issue).

**Comment by cmungall** [comment]
Will try and take a look … any chance of a minimal example?

**Comment by matentzn** [comment]
The above example is a BOT module of the `cerebral vascular congestion` term haha. Speaks for the module type. So short of randomly deleting classes and see if the issue persists I don't know.. Did you try the above and find it too big?

**Comment by cmungall** [comment]
well it's just examples without IDs and readable class names are easier...

...but I know what's happening. It doesn't materialize this by design.

let's take a look:

```bash
oak -i tests/input/mp-test.json viz MP:0010023 UBERON:0002037 -p i,p,UPHENO:0000003
```

<img width="516" alt="image" src="https://user-images.githubusercontent.com/50745/162353143-5b5fe3ba-af9f-4fe4-9586-1077a258a35e.png">

(blue = part of)

it's not shown because it's redundant with the edge to CBV. It doesn't materialize redundant edges by design. If you do want those then that would be a new robot PR/feature request. This would be trivial as the functionality is there in the EMR. However, the results would be useless for many purposes.

If you really want all entailed edges, just use relation-graph

Note the question of what counts as "redundant" here is not trivial, there is a first pass at a vocabulary here: https://github.com/balhoff/relation-graph/issues/63 -- however, I think for robot purpuses materialize is designed for direct so this issue can be closed?

**Comment by matentzn** [comment]
THANK YOU @cmungall this is a great analysis and much appreciated! I know now what to do!
